#!/usr/bin/env bash
sed -i 's/user\user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i "s/80/8080/listen 8080;/g' /etc/nginx/sites-available/default
service nginx reload
nginx_user=$(ps aux | grep "nginx: master process" | awk '{print $1}'); [ "$nginx_user" == "nginx" ] && echo "Nginx is running as the nginx user"
nc -z 0 8080 && echo "Nginx is listening on port 8080"
